export const FP_UPDATE_VALUE = 'FP_UPDATE_VALUE';
export const FP_SET_ERROR = 'FP_SET_ERROR';

export const FP_OTP_MATCH_PROGRESS = 'FP_OTP_MATCH_PROGRESS';
export const FP_OTP_MATCH_SUCCESS = 'FP_OTP_MATCH_SUCCESS';
export const FP_OTP_MATCH_ERROR = 'FP_OTP_MATCH_ERROR';
export const FP_OTP_MATCH_CLEAR_API_STATE = 'FP_OTP_MATCH_CLEAR_API_STATE';

export const FP_OTP_SET_NEW_PASSWORD_PROGRESS = 'FP_OTP_SET_NEW_PASSWORD_PROGRESS';
export const FP_OTP_SET_NEW_PASSWORD_SUCCESS = 'FP_OTP_SET_NEW_PASSWORD_SUCCESS';
export const FP_OTP_SET_NEW_PASSWORD_ERROR = 'FP_OTP_SET_NEW_PASSWORD_ERROR';
export const FP_OTP_SET_NEW_PASSWORD_CLEAR_API_STATE = 'FP_OTP_SET_NEW_PASSWORD_CLEAR_API_STATE';

export const FP_SEND_OTP_PROGRESS = 'FP_SEND_OTP_PROGRESS';
export const FP_SEND_OTP_SUCCESS = 'FP_SEND_OTP_SUCCESS';
export const FP_SEND_OTP_ERROR = 'FP_SEND_OTP_ERROR';
export const FP_SEND_OTP_CLEAR_API_STATE = 'FP_SEND_OTP_CLEAR_API_STATE';

export const FP_CLEAR_RESET_PASSWORD_STATE = 'FP_CLEAR_RESET_PASSWORD_STATE';
export const FP_CLEAR_OTP_STATE = 'FP_CLEAR_OTP_STATE';
export const FP_CLEAR_STATE = 'FP_CLEAR_STATE';
