export const LOGIN_UPDATE_VALUE = 'LOGIN_UPDATE_VALUE';
export const LOGIN_SET_ERROR = 'LOGIN_SET_ERROR';
export const LOGIN_PROGRESS = 'LOGIN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CLEAR_API_STATE = 'LOGIN_CLEAR_API_STATE';
export const LOGIN_CLEAR_STATE = 'LOGIN_CLEAR_STATE';
